In [52]:
#Introduction to Numpy & Creating Arrays.

In [8]:
import numpy as np

In [2]:
arr = [6,7,8,9] 

In [3]:
print(type(arr))

<class 'list'>


In [4]:
a = np.array(arr)

In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(a.shape)
print(a.dtype)
print(a.ndim)

(4,)
int32
1


In [33]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
b.shape

[[1 2 3]
 [4 5 6]]
2


(2, 3)

In [ ]:
#In-built functions.

In [34]:
np.random.random((2,3))

array([[0.70280629, 0.10496724, 0.42562521],
       [0.27937122, 0.97064994, 0.33979711]])

In [35]:
np.zeros((2,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#Intra-operability of Arrays and Scalars.

In [12]:
c = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

c+d


array([[13., 13., 13.],
       [10., 10., 10.]])

In [13]:

c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [14]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [15]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [ ]:
#Indexing with arrays & using arrays for preprocessing.

In [18]:
a[0]

6

In [19]:
a[3]

0

In [20]:
b[0,0]

1

In [21]:
b[1,2]

6

In [22]:
c[0,1]

8.0

In [23]:
d[1,0:2]

array([9., 8.])

In [25]:
e = np.array([[10,11,12],[13,14,15],
             [16,17,18],[19,20,21]])

In [28]:
#Slicing
e[:3,:2] 

array([[10, 11],
       [13, 14],
       [16, 17]])

In [38]:
#Integer indexing

In [39]:
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [40]:
#boolean indexing meeting specified condition

In [41]:
e[e>15]

array([16, 17, 18, 19, 20, 21])

In [ ]:
#Extra code(In-built mathematical functions).

In [42]:
#sum of all the elements of array.
e.sum()

186

In [43]:
#Mean of array.
e.mean()

15.5

In [44]:
#Minimum Value in arrays.
e.min()

10

In [45]:
#Standard Deviation of arrays.
e.std()

3.452052529534663

In [46]:
#Variance of arrays.
e.var()

11.916666666666666